name: softbrake
description: "An app that adds deliberate friction to help people slow down from endless scrolling."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.2
  flutter_colorpicker: ^1.0.3
  image_picker: ^1.0.4
  crop_your_image: ^2.0.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - VERSION.txt
    - assets/images/
